query IndexData {
    keyValuePairCollection(where: {
        key_in: ["Name", "Tagline", "GitHub URL", "LinkedIn URL", "Website URL"]
    }) {
        items {
            ...KeyValuePairData
        }
    },
    setOfProjectsCollection(where: {
        id: "benjaminsmith.dev"
    }, limit: 1) {
        items {
            featuredProjectsCollection {
                items {
                    ...FeaturedProjectIndex
                }
            },
            notFeaturedProjectsCollection {
                items {
                    ...NotFeaturedProjectIndex
                }
            }
        }
    },
    positionCollection {
        items {
            ...PositionIndex
        }
    },
    awardCollection {
        items {
            ...AwardIndex
        }
    },
    setOfAnnouncementsCollection(where: {
        id: "benjaminsmith.dev"
    }, limit: 1) {
        items {
            featuredAnnouncementsCollection {
                items {
                    ...FeaturedAnnouncementIndex
                }
            }
        }
    }
}

fragment KeyValuePairData on KeyValuePair {
    key,
    value
}

fragment PositionIndex on Position {
    company,
    companyUrl,
    position,
    startDate,
    endDate,
    description,
    points
}

fragment AwardIndex on Award {
    organization,
    organizationUrl,
    award,
    date,
    description,
    submissionUrl,
    submissionProject {
        title
    }
}

fragment FeaturedAnnouncementIndex on Announcement {
    title,
    information,
    date
}

fragment FeaturedProjectIndex on Project {
    title,
    url,
    codeUrl,
    tagline,
    mediaCollection(limit: 1) {
        items {
            title,
            width,
            height,
            url(transform: {
                format: WEBP,
                width: 800,
                quality: 50
            })
        }
    }
}

fragment NotFeaturedProjectIndex on Project {
    title,
    url,
    codeUrl,
    tagline
}