query Profile {
    keyValuePairCollection(where: {
        key_in: ["Name", "Tagline", "GitHub URL", "LinkedIn URL", "Website URL"]
    }) {
        items {
            key,
            value
        }
    }
}