query ProjectPage($project: String) {
    projectCollection(where: {
        title: $project
    }, limit: 1) {
        items {
            ...ProjectPage
        }
    }
}

fragment ProjectPage on Project {
    title,
    url,
    codeUrl,
    mediaCollection {
        items {
            ...ProjectAsset
        }
    },
    tagline,
    collaborators,
    skillsCollection {
        items {
            title
        }
    },
    description
}

fragment ProjectAsset on Asset {
    title,
    url(transform: {
        format: WEBP,
        # Maximum width
        width: 1920
    }),
    width,
    height
}